[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "recipes-lu"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.0,<4"
flask = ">=3.1.0,<4"
